name: build-extension
on:
  push:
    tags:
      - 'v*'

# Needed so the release step can upload assets
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json

      - name: Install dependencies
        working-directory: extension
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build extension
        working-directory: extension
        run: npm run build

      - name: Prepare extension files
        working-directory: extension
        run: |
          # Copy necessary files to dist folder
          cp manifest.json dist/
          cp src/options/index.html dist/
          cp -r public/icons dist/

      - name: Create Chrome Web Store ZIP
        working-directory: extension/dist
        run: |
          # Create ZIP with files at root level (Chrome Web Store requirement)
          zip -r phishguard-lite-${GITHUB_REF_NAME}.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phishguard-lite-${{ github.ref_name }}
          path: extension/dist/phishguard-lite-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: extension/dist/phishguard-lite-${{ github.ref_name }}.zip
