name: build-extension
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json
      - name: Install deps
        working-directory: extension
        run: npm ci
      - name: Build
        working-directory: extension
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phishguard-lite-dist
          path: extension/dist
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            extension/dist/**
